controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

login:
  path: /login
  controller: App\Controller\SecurityController::login

login_check:
  path: /login_check
